// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": "favicon.ico",
        "revision": "7cbcf8be98d3ce63133537d07504db0f"
    },
    {
        "url": "allah.mp3",
        "revision": "6ee1fa6162735c9be6314ada3b770627"
    },
    {
        "url": "anthem.mp3",
        "revision": "b97c33069927ab5993e85bb294bc0c05"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.py",
        "revision": "912a9d55d74613b8f4f07180d0df1fd3"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates new.py",
        "revision": "6f204d68894960c2efd7b6379cfbddab"
    },
    {
        "url": "cv.html",
        "revision": "5ba6636efb40d5119203a5416c98f832"
    },
    {
        "url": "cv10.html",
        "revision": "2094af5f378b923e85e3672b64b350be"
    },
    {
        "url": "cv11.html",
        "revision": "c67ad1e21b351cd8f00db4c2d4afbb47"
    },
    {
        "url": "cv12.html",
        "revision": "1b328841bbb52cfcf19d99ce41f34d02"
    },
    {
        "url": "cv13.html",
        "revision": "0fec112bebebdee87bf3144c8d223ed9"
    },
    {
        "url": "cv14.html",
        "revision": "8efa87b27e5cc816c1358f21488a6971"
    },
    {
        "url": "cv15.html",
        "revision": "0ddc0f150f515c65c48ff28c03007daf"
    },
    {
        "url": "cv16.html",
        "revision": "fc40b20602f7eccc9daf50b11e589a16"
    },
    {
        "url": "cv17.html",
        "revision": "3dea76079ac0a4c2431445db67feb23b"
    },
    {
        "url": "cv18.html",
        "revision": "0ddc0f150f515c65c48ff28c03007daf"
    },
    {
        "url": "cv19.html",
        "revision": "bb1d730544c16782dac97f1762baaf5b"
    },
    {
        "url": "cv2.html",
        "revision": "02e1044796fe43a1123d1c9fe23c8e1b"
    },
    {
        "url": "cv3.html",
        "revision": "fa07a3d478bf438141cebafd44b6c3ea"
    },
    {
        "url": "cv4.html",
        "revision": "985d88c45117693255b392c3647001d7"
    },
    {
        "url": "cv5.html",
        "revision": "ec57bcc9f1b9488ae04bcb9675e5a9fc"
    },
    {
        "url": "cv6.html",
        "revision": "2bff779870476f7b856035a5142ec73b"
    },
    {
        "url": "cv7.html",
        "revision": "6d1cca810c551509f859c89fb5ec22d1"
    },
    {
        "url": "cv8.html",
        "revision": "40eaa7153e1e4d43c4a763edb561afd7"
    },
    {
        "url": "cv9.html",
        "revision": "72224705a42c1b0a41bb80d485558d47"
    },
    {
        "url": "Duroods.txt",
        "revision": "8c3fb4c453aa5083a1d4a499e5f36a3d"
    },
    {
        "url": "Duroods2.txt",
        "revision": "02cb81e55d14bfa18d76f1b1176f46e5"
    },
    {
        "url": "exp.png",
        "revision": "ebb965ddb6da25270e5c3efbfeeec37f"
    },
    {
        "url": "fb.jpg",
        "revision": "7d57c25d1b28373b2c487c6ca7c8d226"
    },
    {
        "url": "filelist.txt",
        "revision": "52c85d452b2076907eca54f0b0c0b0a4"
    },
    {
        "url": "goldandSilverPrice.html",
        "revision": "e61932616d5bf650e5b03f7f9b76e140"
    },
    {
        "url": "google43faf8d78a699bd4.html",
        "revision": "2dc5557d04f2ac5181bfd5f27cdd7a66"
    },
    {
        "url": "gsap.min.js",
        "revision": "448deef673e4d919eb5592410f72533e"
    },
    {
        "url": "index.html",
        "revision": "7a8af9a318478fd1ede8786553188e99"
    },
    {
        "url": "index3.html",
        "revision": "0fc48b0498c17b89323858b400a5cb6a"
    },
    {
        "url": "index4.html",
        "revision": "a22ddae4928004f54b64cfdd9d8163ce"
    },
    {
        "url": "index5.html",
        "revision": "0c77583450e912ffef9298fd5715a529"
    },
    {
        "url": "index6.html",
        "revision": "4dbb914498ad60d99df965309b90f43f"
    },
    {
        "url": "indexbk.html",
        "revision": "1f3828ea633409a9dfff89782c2f549d"
    },
    {
        "url": "indexMsword.html",
        "revision": "228e902d9041f6cb109eb7927c5baeab"
    },
    {
        "url": "indexonverted.html",
        "revision": "756a8ee2d5c34e43d32e0895932f543e"
    },
    {
        "url": "indexonverted2.html",
        "revision": "2e36c09cadd530accd23d1dfbc958e29"
    },
    {
        "url": "islam.html",
        "revision": "930a60f1fce267040a019c9246f150a6"
    },
    {
        "url": "islam2.html",
        "revision": "a7eae1c766372216a8cd54443d5fd7d7"
    },
    {
        "url": "jameel-noori-nastaleeq.ttf",
        "revision": "0feabd6c9714cc4bb922bfb16e1ef20f"
    },
    {
        "url": "jquery-ui.js",
        "revision": "cbc65ff85e08b21d7e0c0394fbf3a371"
    },
    {
        "url": "jquery.html",
        "revision": "c77f00db5a75e5187a8d6750c8aa2e58"
    },
    {
        "url": "jquery.js",
        "revision": "00727d1d5d9c90f7de826f1a4a9cc632"
    },
    {
        "url": "logo.jpg",
        "revision": "982b8101d5eff0244d33d0cfb47bd0a3"
    },
    {
        "url": "manifest.json",
        "revision": "dbbcf1c2870a0eb29e927842e5aaea9c"
    },
    {
        "url": "muhammad(pbuh).html",
        "revision": "168c6ad1170fb7141a8eedb4c9a322f8"
    },
    {
        "url": "muhammad.mp3",
        "revision": "66193d07af6cc74182e19efc10755bca"
    },
    {
        "url": "myresume.docx",
        "revision": "b27f74865a5e16920d77eefdb86e0e4a"
    },
    {
        "url": "myresumeold.docx",
        "revision": "ee13bdd6e26b13f25a8386dbe0bd6900"
    },
    {
        "url": "offline.html",
        "revision": "abc5f7febfe55dd908c8c0718687bfd5"
    },
    {
        "url": "pak.gif",
        "revision": "0682d2263857f1cc788a8488eecbf76b"
    },
    {
        "url": "prophet.html",
        "revision": "344ac832ad4ca0591461e30625bdab46"
    },
    {
        "url": "prophetBirth_1.html",
        "revision": "39ec3fba6f62fa32fd1c57412995f2c1"
    },
    {
        "url": "README.md",
        "revision": "1e7e685ea85ac797c658c9d3ac984b2d"
    },
    {
        "url": "resume.css",
        "revision": "4b5f5640f2b04b8e863242caa6317881"
    },
    {
        "url": "ScrollTrigger.min.js",
        "revision": "9f0592f8748a65b0c765a9dc16e8965f"
    },
    {
        "url": "sitemap.xml",
        "revision": "baa58927a14b5cffd79a5bdbb19302ea"
    },
    {
        "url": "srt.png",
        "revision": "aa922e39d3d85115ce306dd1eeeff653"
    },
    {
        "url": "sw.js",
        "revision": "78c9d76d54bc1c861c825e35973ba780"
    },
    {
        "url": "three.min.js",
        "revision": "17ae6ddcbd1d206495dcd2e45508dd1c"
    },
    {
        "url": "ttab.png",
        "revision": "25625b16abc3cc1623bbac0c7322c361"
    },
    {
        "url": "twit.png",
        "revision": "4c6b77a39c06c9670dba1ac6b67940e7"
    },
    {
        "url": "wtsp.jpg",
        "revision": "9c4547952e50513313e52882c2121ade"
    },
    {
        "url": "Yasin.ico",
        "revision": "49e546550af284d5db439a55f0d1656f"
    },
    {
        "url": "Yasin.jpg",
        "revision": "7bcbbefc123eee1d84d64353893555ef"
    },
    {
        "url": "yasin.pdf",
        "revision": "94965e50d9602e7560e54bb1bb16a233"
    },
    {
        "url": "yasin.png",
        "revision": "ad3c315ae393062562f4146432bea831"
    },
    {
        "url": "Yasin2.ico",
        "revision": "4c3c7dba9285eecd68c23b402dbbdd57"
    },
    {
        "url": "Yasin2.png",
        "revision": "0afded513835879a017c8a483d6502dd"
    },
    {
        "url": "YasinSearch.HTML",
        "revision": "e10030dea3cecdda2b7b0b86a475e8a2"
    },
    {
        "url": "YasinSearch2.HTML",
        "revision": "6ae631863409d7c2facbee82e7d61585"
    },
    {
        "url": "YasinSearch3.HTML",
        "revision": "881ee62250decf8407fee1cca49f0eec"
    },
    {
        "url": "yt.jpg",
        "revision": "dc5e9de32ee6daf2ddc444f859efc788"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}