// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": "favicon.ico",
        "revision": "7cbcf8be98d3ce63133537d07504db0f"
    },
    {
        "url": "allah.mp3",
        "revision": "6ee1fa6162735c9be6314ada3b770627"
    },
    {
        "url": "anthem.mp3",
        "revision": "b97c33069927ab5993e85bb294bc0c05"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.pyw",
        "revision": "d3ceb161cfab9e9c5f40a93e15e5be27"
    },
    {
        "url": "Copy (2) of index.html",
        "revision": "88a1eec5d46842e5590eedb6261f70c1"
    },
    {
        "url": "Copy of index.html",
        "revision": "133bdc2ad513ee24221930b0c8f71e76"
    },
    {
        "url": "Copy of yasin sketch.png",
        "revision": "558b7e488db001530968b9652f9c8ce0"
    },
    {
        "url": "cv.html",
        "revision": "13af951175a1efc18082e45b67b338bc"
    },
    {
        "url": "cv10.html",
        "revision": "cb696b01c3d001d28a2f8b6429422df2"
    },
    {
        "url": "cv11.html",
        "revision": "770a09fce8e23e759bd7adcd603e1fd0"
    },
    {
        "url": "cv12.html",
        "revision": "bf43bae9b667c9b55a4aad7b6342c893"
    },
    {
        "url": "cv13.html",
        "revision": "cf3d46c113749e704f9859654bfe5a89"
    },
    {
        "url": "cv14.html",
        "revision": "068d82b07a0fca2672cc1883d0d04d5d"
    },
    {
        "url": "cv15.html",
        "revision": "e0ae64791270c117d2d703280119e62c"
    },
    {
        "url": "cv16.html",
        "revision": "2443cb11d9e6b2bb2a6e2f226daabd97"
    },
    {
        "url": "cv17.html",
        "revision": "2e0c010e472bfea74585143c442a608a"
    },
    {
        "url": "cv18.html",
        "revision": "e0ae64791270c117d2d703280119e62c"
    },
    {
        "url": "cv19.html",
        "revision": "13ace4903c91e7bf121c2dea684de1cb"
    },
    {
        "url": "cv2.html",
        "revision": "54b904bf41c6604d3fb8463d699327b0"
    },
    {
        "url": "cv3.html",
        "revision": "e954b633559258a31304e7e314ac8e29"
    },
    {
        "url": "cv4.html",
        "revision": "befd854f2ce3862151f39573c09f36e3"
    },
    {
        "url": "cv5.html",
        "revision": "fb6a57c3f86b916b374114fa70323baa"
    },
    {
        "url": "cv6.html",
        "revision": "271633b21c5d57e44a8d553389be5bfb"
    },
    {
        "url": "cv7.html",
        "revision": "989f5127d1a33350290337fbb52ed850"
    },
    {
        "url": "cv8.html",
        "revision": "2bc96ca0a7cffe8bc53a86fe33723bc7"
    },
    {
        "url": "cv9.html",
        "revision": "b84b3fcffff5a5694e5f9c12f33e5414"
    },
    {
        "url": "Duroods.txt",
        "revision": "8c3fb4c453aa5083a1d4a499e5f36a3d"
    },
    {
        "url": "Duroods2.txt",
        "revision": "02cb81e55d14bfa18d76f1b1176f46e5"
    },
    {
        "url": "exp.png",
        "revision": "ebb965ddb6da25270e5c3efbfeeec37f"
    },
    {
        "url": "fb.jpg",
        "revision": "7d57c25d1b28373b2c487c6ca7c8d226"
    },
    {
        "url": "filelist.txt",
        "revision": "52c85d452b2076907eca54f0b0c0b0a4"
    },
    {
        "url": "goldandSilverPrice.html",
        "revision": "d6d19307cc5700b52a0486d6d4eecc84"
    },
    {
        "url": "google43faf8d78a699bd4.html",
        "revision": "2dc5557d04f2ac5181bfd5f27cdd7a66"
    },
    {
        "url": "gsap.min.js",
        "revision": "448deef673e4d919eb5592410f72533e"
    },
    {
        "url": "index.html",
        "revision": "133bdc2ad513ee24221930b0c8f71e76"
    },
    {
        "url": "index3.html",
        "revision": "908160e5191aa4638b1a7f86f7635d76"
    },
    {
        "url": "index4.html",
        "revision": "d286a7519ef37d04380f5ec3c62ebeb1"
    },
    {
        "url": "index5.html",
        "revision": "8e9aeb81aca98656b9b8191f04510dee"
    },
    {
        "url": "index6.html",
        "revision": "4a50d59b89e418818b43c4d71dc770f3"
    },
    {
        "url": "indexbk.html",
        "revision": "cd4261832213ee97576640ef20d69ac0"
    },
    {
        "url": "indexMsword.html",
        "revision": "8f26ab0ef054dc91c09f5322a8b51b63"
    },
    {
        "url": "indexonverted.html",
        "revision": "86ae1a678a5e1f3e331c8599e3463ac4"
    },
    {
        "url": "indexonverted2.html",
        "revision": "6f19d8c8a0cf56bb355a7bb0f22dcb9c"
    },
    {
        "url": "islam.html",
        "revision": "99868bc37b8258f2c6f45ee038db4445"
    },
    {
        "url": "islam2.html",
        "revision": "e79d117d94843bfe661a2043de83b6c1"
    },
    {
        "url": "jameel-noori-nastaleeq.ttf",
        "revision": "0feabd6c9714cc4bb922bfb16e1ef20f"
    },
    {
        "url": "jquery-ui.js",
        "revision": "cbc65ff85e08b21d7e0c0394fbf3a371"
    },
    {
        "url": "jquery.html",
        "revision": "82ccb2af41d52e8ea312d04c53c1065d"
    },
    {
        "url": "jquery.js",
        "revision": "00727d1d5d9c90f7de826f1a4a9cc632"
    },
    {
        "url": "logo.jpg",
        "revision": "982b8101d5eff0244d33d0cfb47bd0a3"
    },
    {
        "url": "manifest.json",
        "revision": "459d31a1e1f70aced024e8174ce3f342"
    },
    {
        "url": "muhammad(pbuh).html",
        "revision": "41219999b37530d217cb28ca47800af9"
    },
    {
        "url": "muhammad.mp3",
        "revision": "66193d07af6cc74182e19efc10755bca"
    },
    {
        "url": "my yasin picture.png",
        "revision": "38ed966b6f93db56eaa79cd7b4f59f2a"
    },
    {
        "url": "myresume.docx",
        "revision": "c2b72863dafc58559a9175160802e5f3"
    },
    {
        "url": "myresumeold.docx",
        "revision": "ee13bdd6e26b13f25a8386dbe0bd6900"
    },
    {
        "url": "offline.html",
        "revision": "ad17d01f02bb01615fbc0509f5aee82a"
    },
    {
        "url": "og_banner.png",
        "revision": "85bab51e01e1420f898af3d6bcf39d8e"
    },
    {
        "url": "pak.gif",
        "revision": "0682d2263857f1cc788a8488eecbf76b"
    },
    {
        "url": "portfolio.html",
        "revision": "be7217c549d07c0dd12389a3cffc9ef0"
    },
    {
        "url": "prophet.html",
        "revision": "69f7b9f1521849d7e9e3b73069439251"
    },
    {
        "url": "prophetBirth_1.html",
        "revision": "82e6f2e1f8857a4f940d580f1099d94e"
    },
    {
        "url": "pwa-register.js",
        "revision": "3ec872e4f752840ad8f85922ff6cebe7"
    },
    {
        "url": "README.md",
        "revision": "1e7e685ea85ac797c658c9d3ac984b2d"
    },
    {
        "url": "resume.css",
        "revision": "4b5f5640f2b04b8e863242caa6317881"
    },
    {
        "url": "ScrollTrigger.min.js",
        "revision": "9f0592f8748a65b0c765a9dc16e8965f"
    },
    {
        "url": "sitemap.xml",
        "revision": "baa58927a14b5cffd79a5bdbb19302ea"
    },
    {
        "url": "srt.png",
        "revision": "aa922e39d3d85115ce306dd1eeeff653"
    },
    {
        "url": "sw.js",
        "revision": "2eda7106da6c74a9ec3b38551efc89a4"
    },
    {
        "url": "three.min.js",
        "revision": "17ae6ddcbd1d206495dcd2e45508dd1c"
    },
    {
        "url": "ttab.png",
        "revision": "25625b16abc3cc1623bbac0c7322c361"
    },
    {
        "url": "twit.png",
        "revision": "4c6b77a39c06c9670dba1ac6b67940e7"
    },
    {
        "url": "wtsp.jpg",
        "revision": "9c4547952e50513313e52882c2121ade"
    },
    {
        "url": "Yasin new.jpg",
        "revision": "1cc33aef68353599cfd5281f6ad28164"
    },
    {
        "url": "yasin sketch 2.png",
        "revision": "abe0b2aebab7931f37e92debdf7107e2"
    },
    {
        "url": "yasin sketch 3.png",
        "revision": "776bc57086df7b6f0806ab70286b7005"
    },
    {
        "url": "yasin sketch.png",
        "revision": "6b54b2d1ef17f671f03e619d00e15545"
    },
    {
        "url": "Yasin.ico",
        "revision": "49e546550af284d5db439a55f0d1656f"
    },
    {
        "url": "yasin.jpg",
        "revision": "b6ada0cbd309c0fc5deebc14bd2c79b9"
    },
    {
        "url": "yasin.pdf",
        "revision": "5eca9ff0235555ffc860790b9f7b046c"
    },
    {
        "url": "yasin.png",
        "revision": "ad3c315ae393062562f4146432bea831"
    },
    {
        "url": "Yasin2.ico",
        "revision": "4c3c7dba9285eecd68c23b402dbbdd57"
    },
    {
        "url": "Yasin2.png",
        "revision": "0afded513835879a017c8a483d6502dd"
    },
    {
        "url": "yasinOld.jpg",
        "revision": "6c85a524df50b3302269dbfbd630e64f"
    },
    {
        "url": "YasinSearch.HTML",
        "revision": "e10030dea3cecdda2b7b0b86a475e8a2"
    },
    {
        "url": "YasinSearch2.HTML",
        "revision": "6ae631863409d7c2facbee82e7d61585"
    },
    {
        "url": "YasinSearch3.HTML",
        "revision": "881ee62250decf8407fee1cca49f0eec"
    },
    {
        "url": "yt.jpg",
        "revision": "dc5e9de32ee6daf2ddc444f859efc788"
    },
    {
        "url": "portfolio_content/data/projects.json",
        "revision": "a6777f85cbb0072060a68c5a971926e0"
    },
    {
        "url": "portfolio_content/docs/myresume.docx",
        "revision": "c2b72863dafc58559a9175160802e5f3"
    },
    {
        "url": "portfolio_content/docs/yasin.pdf",
        "revision": "5eca9ff0235555ffc860790b9f7b046c"
    },
    {
        "url": "portfolio_content/docs/Yasin_Ullah_EuroPass_CV.pdf",
        "revision": "5eca9ff0235555ffc860790b9f7b046c"
    },
    {
        "url": "portfolio_content/images/academy_admissions_screenshot_1769740474935.png",
        "revision": "d269ad25961b6f9978d0edcb21749282"
    },
    {
        "url": "portfolio_content/images/academy_admission_screenshot_1769740206368.png",
        "revision": "fb60c67a0bd81ee9a75271f6765b431d"
    },
    {
        "url": "portfolio_content/images/Al-Furqan-Studio-new_Ayah_1_1.png",
        "revision": "d76a6d3ebcd19f12b9e6a14a8922744c"
    },
    {
        "url": "portfolio_content/images/Al-Furqan-Studio-new_Ayah_2_2.png",
        "revision": "b05580aa4292deb34c42225e782b63fe"
    },
    {
        "url": "portfolio_content/images/bakery_cafe-dashboard.png",
        "revision": "e9efd552a61956d218e9d65fa02e6ba3"
    },
    {
        "url": "portfolio_content/images/bakery_cafe-pos.png",
        "revision": "1fc5c40141da61addc7e42565e516837"
    },
    {
        "url": "portfolio_content/images/bakery_cash-book.png",
        "revision": "1adfa13c4289932f45a8d73096eba158"
    },
    {
        "url": "portfolio_content/images/bakery_dashboard.png",
        "revision": "5c4d419f74712771150b4ad58554b2e9"
    },
    {
        "url": "portfolio_content/images/blood_bloodbg.png",
        "revision": "381674024335f11eb1da1d5fd5d3bbdd"
    },
    {
        "url": "portfolio_content/images/blood_Certificate-Ahmed-Khan.png",
        "revision": "3bd52cd2d4bc42c7fc261ad392e3dc20"
    },
    {
        "url": "portfolio_content/images/bookshop_annotated_books_management_page_1769705164955.png",
        "revision": "c909c56d728d77a7e8b895bdf5c12d24"
    },
    {
        "url": "portfolio_content/images/bookshop_annotated_cart_and_sales_page_1769705368047.png",
        "revision": "e799c31d849efdde6fc126e29b669e25"
    },
    {
        "url": "portfolio_content/images/ConvertPHPAppToExe_logo.png",
        "revision": "ce8ddbeb705fe504613cc8cd132f4bfd"
    },
    {
        "url": "portfolio_content/images/haircut_annotated_appointments_page_v2_1769753286698.png",
        "revision": "92346d2b5c73eeaf0fa3e288da195f30"
    },
    {
        "url": "portfolio_content/images/haircut_annotated_customers_page_v2_1769753288565.png",
        "revision": "e91ab2e77ad3c8fe879590b124247e9c"
    },
    {
        "url": "portfolio_content/images/hospitalManageSaaS_logo-512.png",
        "revision": "7761ee8150363fcd5dc1d67a29d6b7df"
    },
    {
        "url": "portfolio_content/images/hospitalManageSaaS_logo.png",
        "revision": "7761ee8150363fcd5dc1d67a29d6b7df"
    },
    {
        "url": "portfolio_content/images/HotelSaaS_hotel-01-16-2026_11_35_AM_part1.png",
        "revision": "fd7f1fc199415bca9af4c012d1ac8027"
    },
    {
        "url": "portfolio_content/images/HotelSaaS_screenshot_Superadmin_dashboard.png",
        "revision": "f88706d61f19ba30309afc292049e02a"
    },
    {
        "url": "portfolio_content/images/inventory_BNI-Enterprises-Bike-Dealer-Management-System-04-20-2026_05_59_PM.png",
        "revision": "15b8311c1d984e27e954ac659aa7ef35"
    },
    {
        "url": "portfolio_content/images/madrasa_All_ID_Cards_View.png",
        "revision": "bbafe4417eb40ebfe4cfb83d390315e9"
    },
    {
        "url": "portfolio_content/images/madrasa_bgc.png",
        "revision": "d8de28ba10bbeaecf2ed77dc49f55ece"
    },
    {
        "url": "portfolio_content/images/og_banner.jpg",
        "revision": "b8a66c053ceca3e167cea9ca6e1d22dd"
    },
    {
        "url": "portfolio_content/images/og_banner.png",
        "revision": "85bab51e01e1420f898af3d6bcf39d8e"
    },
    {
        "url": "portfolio_content/images/yasin_avatar.png",
        "revision": "0283e7656d3863fb08b97060e0d8d82a"
    },
    {
        "url": "portfolio_content/images/yasin_profile.jpg",
        "revision": "2c90d55abb2b233bee9701f8fd9c98d3"
    },
    {
        "url": "portfolio_content/images/zakat-cal_logo.png",
        "revision": "72d33ff182712327094b50539dfb5bec"
    },
    {
        "url": "portfolio_content/images/zakat-cal_logo2.png",
        "revision": "bfaef3a4310879d47e5a3b3024d3e86f"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}